version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: day11
    ports:
      - "5433:5432"
    volumes:
      - /Users/apple/Desktop/volume-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: express_backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 8000
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      DB_NAME: day11
      DB_HOST: postgres
      DB_DIALECT: postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
